### ISSUE TITLE
Consistency in design

### ISSUE THREAD

**Issue by jema28** [FACN4/week8-wdgaf#67]
Love the design overall! A few things to consider: 
- I would keep the picture shape consistent and a similar size on the details page ie. either circle or rectangle.
- Take a look at alignment e.g. with titles and images in the Meet the Grads section. 
- The size of the white header at the top could be reduced or made slightly transparent.
- Think about the focal point of the site and what you want users to look at first.

**Comment by matthall8** [comment]
Thanks Jem. I've changed the shape and the header, hopefully making it easier to see the focal points of the site in the latest commit. I've left the alignment as is for the Meet the Grads section. This is due to style not looking good if it's all left aligned and it looking even worse if the images are left aligned (to match the titles) and the link center aligned. Definitely something we'll bear in mind in the future though.
